### PR TITLE
TTA-23-create-test-suite

### PR DESCRIPTION
**Pull request by ryancwalsh**
https://near-foundation.atlassian.net/jira/software/c/projects/TTA/boards/5?modal=detail&selectedIssue=TTA-23

@sandoche , this is _not_ urgent for you to do Fri.

But when you have a moment, can you please read the Tests section of the Readme and try it out? I want to ensure that the instructions are clear enough and that the tests work for you.

### CODE REVIEW

**Comment by sandoche** [comment]
So I tried to follow the steps for the tests on this branch and I got this error

```
$ pgCreds=postgresql://postgres:toor@localhost:5432/tta_test_db ./server/test_helpers/updateTestData.sh
 --table=temp_test_export_transactions
 --table=temp_test_export_transactions --table=temp_test_export_receipts
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions --table=temp_test_export_transaction_actions
Calling defineTransactionHashesInSql...
yarn run v1.22.19
$ C:\Projects\tx-tracking-app\node_modules\.bin\ts-node --esm ./server/test_helpers/internal/defineTransactionHashesInSql.ts
C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
server/test_helpers/internal/csvToJson.ts(4,22): error TS2307: Cannot find module 'csvjson-csv2json' or its corresponding type declarations.

    at createTSError (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:1433:41)
    at transformSource (C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:400:37)
    at C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:278:53
    at async addShortCircuitFlag (C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:409:15)
    at async ESMLoader.load (node:internal/modules/esm/loader:407:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:11) {
  diagnosticCodes: [ 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Merging transactionHashes.sql with tableDefinitions.sql...
cat: server/test_helpers/internal/transactionHashes.sql: No such file or directory
Calling createTempTablesOfRowsWithSpecificTransactions...
./server/test_helpers/updateTestData.sh: line 22: psql: command not found
Downloading temp tables as schemas + INSERT statements...
./server/test_helpers/updateTestData.sh: line 25: pg_dump: command not found
Dropping temp_test_export_transactions...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Dropping temp_test_export_receipts...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Dropping temp_test_export_execution_outcomes...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Dropping temp_test_export_blocks...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Dropping temp_test_export_action_receipt_actions...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Dropping temp_test_export_transaction_actions...
./server/test_helpers/updateTestData.sh: line 30: psql: command not found
Deleting temp_test_export_ from the insert statements...
sed: can't read s/temp_test_export_//g: No such file or directory
Deleting public. from the SQL...
sed: can't read s/public.//g: No such file or directory
Deleting other non-sqlite stuff from the SQL...
cleanTheSql.sh finished.
Finished!
```

Note that I am using windows with git-bash/MINGW64

It looks that I need to add some bin to the path. I'll redo a trial after doing so.

**Comment by sandoche** [comment]
I will try to document every step so you can see what to add to the doc.

So after adding postgre bin to the path I got the following:
```sh
$ pgCreds=postgresql://postgres:toor@localhost:5432/tta_test_db ./server/test_helpers/updateTestData.sh
 --table=temp_test_export_transactions
 --table=temp_test_export_transactions --table=temp_test_export_receipts
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions --table=temp_test_export_transaction_actions
Calling defineTransactionHashesInSql...
yarn run v1.22.19
$ C:\Projects\tx-tracking-app\node_modules\.bin\ts-node --esm ./server/test_helpers/internal/defineTransactionHashesInSql.ts
C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
server/test_helpers/internal/csvToJson.ts(4,22): error TS2307: Cannot find module 'csvjson-csv2json' or its corresponding type declarations.

    at createTSError (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\Projects\tx-tracking-app\node_modules\ts-node\src\index.ts:1433:41)
    at transformSource (C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:400:37)
    at C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:278:53
    at async addShortCircuitFlag (C:\Projects\tx-tracking-app\node_modules\ts-node\src\esm.ts:409:15)
    at async ESMLoader.load (node:internal/modules/esm/loader:407:20)
    at async ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:11) {
  diagnosticCodes: [ 2307 ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Merging transactionHashes.sql with tableDefinitions.sql...
cat: server/test_helpers/internal/transactionHashes.sql: No such file or directory
Calling createTempTablesOfRowsWithSpecificTransactions...
psql: warning: extra command-line argument "server/test_helpers/internal/createTempTablesOfRowsWithSpecificTransactions.sql" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Downloading temp tables as schemas + INSERT statements...
pg_dump: error: too many command-line arguments (first is "--table=temp_test_export_transactions")
Try "pg_dump --help" for more information.
Dropping temp_test_export_transactions...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_transactions;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Dropping temp_test_export_receipts...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_receipts;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Dropping temp_test_export_execution_outcomes...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_execution_outcomes;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Dropping temp_test_export_blocks...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_blocks;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Dropping temp_test_export_action_receipt_actions...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_action_receipt_actions;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Dropping temp_test_export_transaction_actions...
psql: warning: extra command-line argument "DROP TABLE IF EXISTS temp_test_export_transaction_actions;" ignored
psql: error: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "tta_test_db" does not exist
Deleting temp_test_export_ from the insert statements...
sed: can't read s/temp_test_export_//g: No such file or directory
Deleting public. from the SQL...
sed: can't read s/public.//g: No such file or directory
Deleting other non-sqlite stuff from the SQL...
cleanTheSql.sh finished.
Finished!
```

A bit better

**Comment by ryancwalsh** [comment]
@sandoche Hmm, your error shows `error TS2307: Cannot find module 'csvjson-csv2json' or its corresponding type declarations.` but it exists in `server/package.json`.

**Comment by sandoche** [comment]
I will do the steps of the quick start to create the db (my bad)! Maybe add a line saying to make sure the quick start steps had been done?

**Comment by ryancwalsh** [comment]
@sandoche Can you please commit to the Readme any steps that need to be added or edited? That might be easiest. Thanks.

**Comment by sandoche** [comment]
Ok I will

**Comment by sandoche** [comment]
Btw not sure if it's a windows thing, but `psql postgres -U testuser` didn't work I had to do `psql postgres testuser` instead

**Comment by sandoche** [comment]
I comment here for now so I don't forget to fix:
```
CREATE DATABASE ttatestdb;
GRANT ALL PRIVILEGES ON DATABASE tta_test_db TO testuser;
```

Should be tta_test_db everywhere

**Comment by sandoche** [comment]
@ryancwalsh 

Now I am stuck with
`error TS2307: Cannot find module 'csvjson-csv2json' or its corresponding type declarations.`

That you can see above.

I get it when I (or the script) run
`yarn ts-node  --esm ./server/test_helpers/internal/defineTransactionHashesInSql.ts`

**Comment by sandoche** [comment]
Adding `csvjson-csv2json` to the root package.json fixes it.

Should I add it to the root `package.json`?

**Comment by sandoche** [comment]
@ryancwalsh After adding the `csvjson-csv2json` to the root package.json it works but it hangs for a while, it's been almost 20 min and it's still not finished (?)
```
$ pgCreds=postgresql://postgres:toor@localhost:5432/tta_test_db ./server/test_helpers/updateTestData.sh
 --table=temp_test_export_transactions
 --table=temp_test_export_transactions --table=temp_test_export_receipts
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions
 --table=temp_test_export_transactions --table=temp_test_export_receipts --table=temp_test_export_execution_outcomes --table=temp_test_export_blocks --table=temp_test_export_action_receipt_actions --table=temp_test_export_transaction_actions
Calling defineTransactionHashesInSql...
yarn run v1.22.19
$ C:\Projects\tx-tracking-app\node_modules\.bin\ts-node --esm ./server/test_helpers/internal/defineTransactionHashesInSql.ts
Done in 2.02s.
Merging transactionHashes.sql with tableDefinitions.sql...
Calling createTempTablesOfRowsWithSpecificTransactions...
psql: warning: extra command-line argument "server/test_helpers/internal/createTempTablesOfRowsWithSpecificTransactions.sql" ignored
```

Is it the expected behavior, how long does it normally take?

**Comment by sandoche** [comment]
I tried to run `yarn test` anyway and I have similar issue, of missing dependencies because they are in `./server/package.json` and not in the root folder.

Also `DOTENV_CONFIG_PATH=.env.test jest` does not work I had to remove `DOTENV_CONFIG_PATH=.env.test` because windows does not support this :/

**Comment by ryancwalsh** [comment]
Hmm, I think `csvjson-csv2json` shouldn't need to be in the root package.json. 

Bummer about env vars not being able to be set on the same line as the command. https://superuser.com/a/950944/74576 shows possible workarounds in Windows. But have you tried Git BASH on Windows? https://gitforwindows.org/ I vaguely remember it solving problems like this.

**Comment by sandoche** [comment]
I made this commit [05ac8e8](https://github.com/NEARFoundation/tx-tracking-app/pull/16/commits/05ac8e849ba6eddf0fbbe5c76cb6d995f5d4cfe2) to fix the issues I've seen so far with the doc.

I think it needs some line about which indexer pgsql to use but I still haven't managed to make it work.

**Comment by ryancwalsh** [comment]
@sandoche I talked with Robert yesterday, and since I don't think this PR review is important enough to block me, I'll go ahead and merge it. Then I'll schedule a long meeting with you where we can have you review the concepts using VSC Live Share (since your machine isn't letting you connect to Postgresql).

**Pull request merged**
