### PR TITLE
Tta 33 fix the broken crawler

### PR DESCRIPTION
**Pull request by ryancwalsh**

### CODE REVIEW

**Comment by ryancwalsh** [comment]
@sandoche  The main point of this PR is to use `await Promise.all` to run commands in parallel instead of awaiting each async function individually, missing out on the benefit of async.

Also, this PR fixes a bug of `round()` for '' values.

**Comment by ryancwalsh** [comment]
@sandoche I think the 127.0.0.1 breaks the app on Mac, but we'll figure out a fix later.

Can you please review this PR and also https://github.com/NEARFoundation/tx-tracking-app/pull/23? Thanks

**Comment by ryancwalsh** [comment]
@sandoche You can focus on the other PR for now. I saw some weird behavior, which may be problems with this PR, or hopefully it's related to the current problems with our indexer. But I want to resolve whatever they are first.

**Comment by sandoche** [comment]
@ryancwalsh let me know when this PR is ready to be reviewed, I'll do this one only for now https://github.com/NEARFoundation/tx-tracking-app/pull/23

**Pull request closed without merging**
