### PR TITLE
Dev 16 app on aws

### PR DESCRIPTION
**Pull request by nickallevato**

### CODE REVIEW

**Comment by ryancwalsh** [comment]
@nickallevato I had deleted `docker/backend/README.md` at https://github.com/NEARFoundation/tx-tracking-app/commit/5601d9b152d0c3416ddccefc2a68f7347e82f14b and it seems to be recreated here in this branch.

Can you please delete it again (assuming it's stale), or maybe even better would be to edit `docker/backend/README.md` or `README.md` with anything helpful that we should all know? 

Thanks!

**Comment by ryancwalsh** [comment]
@nickallevato E.g. I see that https://near-foundation.atlassian.net/browse/DEV-53 is marked "Done", so it would be great to have the main root Readme teach how to run the app locally. Thanks.

**Comment by ryancwalsh** [comment]
@nickallevato Just let me know when the comments above are addressed and you'd like me to merge. Thanks.

**Comment by nickallevato** [comment]
i removed the readme. 
there are also, i think, several other files that are stale and need to be removed.
example (package.json) in the root of the project.

update: I went through all the files i think are no longer needed and added the removal in c3c4a97 and de0617a

**Pull request merged**
